# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# https://github.com/marketplace/actions/github-action-for-yarn
name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: dashboard-test # will run `yarn test` command
